spring.application.name=recuperacao

# Configuração da Conexão
spring.datasource.url=jdbc:h2:file:./data/oficinaweg
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console do H2 (Para você ver as tabelas no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Criar as tabelas automaticamente baseado nas suas @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true